import type { SiteLocale } from '~~/utils/site-locale'
import { computed } from 'vue'
import { useSiteLocale } from './useSiteLocale'

const copy = {
    en: {
        seoTitle: 'Pricing | Castrel',
        seoDescription: 'Castrel plans and pricing',
        pageTitle: 'Pricing',
        pageSubtitle: 'Start with a free trial. Demo data is provided and no payment method is required.',
        billingMonthly: 'Monthly',
        billingYearly: 'Yearly',
        yearlyDiscount: '17% off',
        faqTitle: 'FAQ',
        planFree: {
            title: 'Free Plan',
            description: 'For individual users and pilot trials in ops teams',
            features: [
                'Full product features',
                'Standard data sources ready out of the box',
                '1 user seat',
                'Up to 1 automation task',
                '2,000 points included at sign-up',
                'Community support',
            ],
            button: 'Start Free',
        },
        planPro: {
            title: 'Pro Plan',
            description: 'For SRE and Ops engineers, teams up to 5 users',
            features: [
                'Full product features',
                'Standard data sources ready out of the box',
                '5 user seats',
                'Up to 5 automation tasks',
                '10,000 points refreshed monthly',
                'Optional permanent points add-on',
                'Dedicated tenant + standard RBAC controls',
                'Data is not used for model training',
                'Feishu group online support',
                'Paid-user dedicated support (5x8)',
            ],
            button: 'Start Pro',
            billingMonthly: '/month',
            billingYearly: '/year',
            faqQuestion: 'What is the difference between monthly and yearly Pro billing?',
        },
        planEnterprise: {
            title: 'Enterprise Plan',
            description: 'For SRE and Ops organizations with teams larger than 10 users.',
            features: [
                'Full product features',
                'BYOM (bring your own LLM) support',
                'Enterprise SSO integration and audit logs',
                'Unlimited automation tasks',
                'Annual subscription with a shared points pool',
                'Additional points available on demand',
                'Multi-tenant enterprise support',
                'Standard RBAC controls',
                'Data is not used for model training',
                'Private deployment and custom delivery',
                'Dedicated delivery engineer and support group',
            ],
            button: 'Contact Sales',
        },
        faq: {
            proBillingAnswer: 'Features are the same. The difference is billing cadence: monthly is billed every month, while yearly is paid once and effectively gives about two months free.',
            pointsQuestion: 'What if we run out of points?',
            pointsAnswer: 'You can buy permanent points on demand, starting at ¥50 for 5,000 points. Enterprise plans also support shared pools and expansion packs.',
            overseasQuestion: 'Can overseas teams purchase directly?',
            overseasAnswer: 'Online payment is currently available only in mainland China. For overseas purchase, contact sales for manual procurement.',
            enterpriseQuestion: 'Does Enterprise support private deployment and SSO?',
            enterpriseAnswer: 'Yes. Enterprise supports private deployment, enterprise SSO, audit logs, and dedicated delivery support.',
        },
        salesModal: {
            title: 'Contact Sales',
            name: 'Name',
            phone: 'Phone',
            company: 'Company Name',
            workEmail: 'Work Email Address',
            jobTitle: 'Job Title',
            useCase: 'Expected Use Case',
            namePlaceholder: 'Your full name',
            phonePlaceholder: 'Primary contact phone number',
            companyPlaceholder: 'Legal company name',
            workEmailPlaceholder: 'you@company.com',
            jobTitlePlaceholder: 'Your role or title',
            useCasePlaceholder: 'Describe your expected scenario, team size, and target timeline',
            requiredError: 'Please complete required fields: phone and company name.',
            invalidPhoneError: 'Invalid phone format. Please check and try again.',
            submitError: 'Submission failed, please try again later.',
            submit: 'Submit',
        },
    },
    zh: {
        seoTitle: '定价 | Castrel',
        seoDescription: 'Castrel 套餐与定价',
        pageTitle: '定价',
        pageSubtitle: '可免费试用，提供演示数据，无需绑定支付方式。',
        billingMonthly: '包月',
        billingYearly: '包年',
        yearlyDiscount: '17% off',
        faqTitle: '常见问题',
        planFree: {
            title: '免费版',
            description: '适合个人用户，运维团队试用',
            features: [
                '产品全功能',
                '标准数据源开箱即用',
                '1 个用户席位',
                '最多创建 1 个自动化任务',
                '注册赠送 2000 积分',
                '社区支持',
            ],
            button: '免费开始',
        },
        planPro: {
            title: '专业版',
            description: '适合 SRE、运维工程师，运维团队 ≤ 5 人',
            features: [
                '产品全功能',
                '标准数据源开箱即用',
                '5 个用户席位',
                '最多创建 5 个自动化任务',
                '每月刷新 10000 积分',
                '可加购永久积分',
                '专属租户 + RBAC 标准权限管控',
                '数据不用于大模型训练',
                '飞书群社区在线支持',
                '付费用户专属支持（5x8）',
            ],
            button: '立即开通',
            billingMonthly: '/月',
            billingYearly: '/年',
            faqQuestion: '专业版包月和包年有什么区别？',
        },
        planEnterprise: {
            title: '企业版',
            description: '适合 SRE、运维工程师，运维团队 > 10 人',
            features: [
                '产品全功能',
                'BYOM（企业自带 LLM）支持',
                '企业 SSO 集成、审计日志',
                '无限创建自动化任务',
                '按年签署订阅合同，团队共享积分池',
                '超额积分可按需扩展购买',
                '多企业租户支持',
                'RBAC 标准权限管控',
                '数据不用于大模型训练',
                '支持私有化部署与业务定制',
                '企业专属交付工程师与支持群',
            ],
            button: '联系我们',
        },
        faq: {
            proBillingAnswer: '功能一致，区别在结算周期。包月按月扣费；包年一次性结算，折算下来约等于 2 个月免费。',
            pointsQuestion: '积分不够了怎么办？',
            pointsAnswer: '可以按需加购永久积分，¥50 起充 5000 积分。企业版支持共享积分池和扩展积分包。',
            overseasQuestion: '海外团队可以直接购买吗？',
            overseasAnswer: '当前线上支付仅对中国大陆开放。海外团队请通过联系销售走人工采购流程。',
            enterpriseQuestion: '企业版支持私有化和 SSO 吗？',
            enterpriseAnswer: '支持。企业版可提供私有化部署、企业 SSO、审计日志及专属交付支持。',
        },
        salesModal: {
            title: '联系销售',
            name: '姓名',
            phone: '手机号',
            company: '公司名称',
            workEmail: '企业邮箱',
            jobTitle: '职位',
            useCase: '期望用途',
            namePlaceholder: '请输入姓名',
            phonePlaceholder: '请输入联系人手机号',
            companyPlaceholder: '请输入公司全称',
            workEmailPlaceholder: '请输入企业邮箱',
            jobTitlePlaceholder: '请输入职位',
            useCasePlaceholder: '请简要描述预期场景、团队规模与上线时间',
            requiredError: '请填写必填信息：手机号、公司名称。',
            invalidPhoneError: '手机号格式不正确，请检查后重试。',
            submitError: '提交失败，请稍后重试。',
            submit: '提交',
        },
    },
} as const

export function getPricingCopy(locale: SiteLocale) {
    return copy[locale]
}

export function usePricingCopy() {
    const { locale } = useSiteLocale()
    return computed(() => getPricingCopy(locale.value))
}
